import { v4 as uuidv4 } from "uuid";
import { usersIds } from "./userData";
import keepingInTouch from "../assets/keeping_in_touch.png";
import discoverNewReads from "../assets/discover_new_reads.png";

export type clubMember = {
  id: string;
  role?: "member" | "moderator" | "owner";
  joinedAt: string;
  isSuspended: boolean;
};

export type ClubBook = {
  bookId: string;
  status: "upcoming" | "current" | "completed";
  startDate?: string;
  endDate?: string;
  addedBy?: string;
  addedAt?: string;
  lastUpdatedBy?: string;
  lastUpdatedAt?: string;
  isWishList?: boolean;
};

export type bookClub = {
  id: string;
  name: string;
  description: string;
  members: clubMember[];
  createdAt: string;
  updatedAt: string;
  imageUrl?: string;
  ownerId: string;
  isPublic: boolean;
  isActive: boolean;
  rating: number;
  tags?: string[];
  location?: string;
  meetingFrequency?: string;
  nextMeeting?: string;
  lastMeeting?: string;
  meetingPlatform?: string;
  currentBook?: ClubBook;
  books?: ClubBook[];
};

export const defaultBookClubs: bookClub[] = [
  {
    id: uuidv4(),
    name: "Book Lovers United",
    description:
      "A vibrant community for passionate readers who love discussing books.",
    members: [
      {
        id: usersIds[2],
        role: "owner",
        joinedAt: "2024-01-15",
        isSuspended: false,
      },
      {
        id: usersIds[3],
        role: "moderator",
        joinedAt: "2024-01-20",
        isSuspended: false,
      },
      {
        id: usersIds[4],
        role: "member",
        joinedAt: "2024-01-25",
        isSuspended: false,
      },
      {
        id: usersIds[5],
        role: "member",
        joinedAt: "2024-02-01",
        isSuspended: false,
      },
      {
        id: usersIds[6],
        role: "member",
        joinedAt: "2024-02-10",
        isSuspended: false,
      },
    ],
    createdAt: "2024-01-10",
    updatedAt: "2024-02-15",
    imageUrl: discoverNewReads,
    ownerId: usersIds[2],
    isPublic: true,
    isActive: true,
    rating: 4.7,
    tags: ["fiction", "mystery", "thriller"],
    location: "Online",
    meetingFrequency: "Weekly",
    nextMeeting: "2024-03-01T19:00:00Z",
    lastMeeting: "2024-02-24T19:00:00Z",
    meetingPlatform: "Zoom",
    currentBook: {
      bookId: "1",
      status: "current",
      startDate: "2024-02-01",
      addedBy: usersIds[2],
      addedAt: "2024-01-20",
    },
    books: [
      {
        bookId: "1",
        status: "current",
        startDate: "2024-02-01",
        addedBy: usersIds[2],
        addedAt: "2024-01-20",
        lastUpdatedBy: usersIds[3],
      },
      {
        bookId: "3",
        status: "upcoming",
        addedBy: usersIds[3],
        addedAt: "2024-01-25",
      },
      {
        bookId: "5",
        status: "completed",
        startDate: "2024-01-01",
        endDate: "2024-01-31",
        addedBy: usersIds[2],
        addedAt: "2023-12-15",
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Sci-Fi Enthusiasts",
    description: "For fans of science fiction and futuristic stories.",
    members: [
      {
        id: usersIds[3],
        role: "owner",
        joinedAt: "2024-01-05",
        isSuspended: false,
      },
      {
        id: usersIds[6],
        role: "moderator",
        joinedAt: "2024-01-12",
        isSuspended: false,
      },
      {
        id: usersIds[7],
        role: "member",
        joinedAt: "2024-01-18",
        isSuspended: false,
      },
      {
        id: usersIds[8],
        role: "member",
        joinedAt: "2024-01-22",
        isSuspended: false,
      },
      {
        id: usersIds[9],
        role: "member",
        joinedAt: "2024-01-28",
        isSuspended: false,
      },
      {
        id: usersIds[10],
        role: "member",
        joinedAt: "2024-02-05",
        isSuspended: false,
      },
    ],
    createdAt: "2024-01-01",
    updatedAt: "2024-02-12",
    imageUrl: keepingInTouch,
    ownerId: usersIds[3],
    isPublic: true,
    isActive: true,
    rating: 4.5,
    tags: ["science fiction", "fantasy", "space"],
    location: "Online",
    meetingFrequency: "Bi-weekly",
    nextMeeting: "2024-03-05T20:00:00Z",
    lastMeeting: "2024-02-20T20:00:00Z",
    meetingPlatform: "Discord",
    currentBook: {
      bookId: "2",
      status: "current",
      startDate: "2024-02-10",
      addedBy: usersIds[3],
      addedAt: "2024-01-15",
    },
    books: [
      {
        bookId: "2",
        status: "current",
        startDate: "2024-02-10",
        addedBy: usersIds[3],
        addedAt: "2024-01-15",
        lastUpdatedBy: usersIds[6],
      },
      {
        bookId: "4",
        status: "upcoming",
        addedBy: usersIds[6],
        addedAt: "2024-02-01",
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Mystery Solvers",
    description:
      "A club for those who love solving mysteries and crime novels.",
    members: [
      {
        id: usersIds[5],
        role: "owner",
        joinedAt: "2024-01-08",
        isSuspended: false,
      },
      {
        id: usersIds[11],
        role: "moderator",
        joinedAt: "2024-01-15",
        isSuspended: false,
      },
      {
        id: usersIds[12],
        role: "member",
        joinedAt: "2024-01-22",
        isSuspended: false,
      },
      {
        id: usersIds[13],
        role: "member",
        joinedAt: "2024-01-29",
        isSuspended: false,
      },
      {
        id: usersIds[14],
        role: "member",
        joinedAt: "2024-02-05",
        isSuspended: false,
      },
    ],
    createdAt: "2024-01-05",
    updatedAt: "2024-02-08",
    imageUrl: keepingInTouch,
    ownerId: usersIds[5],
    isPublic: true,
    isActive: true,
    rating: 4.8,
    tags: ["mystery", "thriller", "crime"],
    location: "Online",
    meetingFrequency: "Monthly",
    nextMeeting: "2024-03-10T18:00:00Z",
    lastMeeting: "2024-02-10T18:00:00Z",
    meetingPlatform: "Google Meet",
    currentBook: {
      bookId: "1",
      status: "current",
      startDate: "2024-02-15",
      addedBy: usersIds[5],
      addedAt: "2024-01-20",
    },
    books: [
      {
        bookId: "1",
        status: "current",
        startDate: "2024-02-15",
        addedBy: usersIds[5],
        addedAt: "2024-01-20",
        lastUpdatedBy: usersIds[11],
      },
      {
        bookId: "2",
        status: "upcoming",
        addedBy: usersIds[11],
        addedAt: "2024-02-01",
      },
      {
        bookId: "3",
        status: "completed",
        startDate: "2024-01-01",
        endDate: "2024-01-31",
        addedBy: usersIds[5],
        addedAt: "2023-12-15",
      },
      {
        bookId: "4",
        status: "completed",
        startDate: "2023-11-01",
        endDate: "2023-12-15",
        addedBy: usersIds[5],
        addedAt: "2023-10-20",
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Fantasy Realm",
    description: "A club for fans of epic fantasy and high fantasy.",
    members: [
      {
        id: usersIds[0],
        role: "owner",
        joinedAt: "2024-01-10",
        isSuspended: false,
      },
      {
        id: usersIds[1],
        role: "moderator",
        joinedAt: "2024-01-17",
        isSuspended: false,
      },
      {
        id: usersIds[2],
        role: "member",
        joinedAt: "2024-01-24",
        isSuspended: false,
      },
      {
        id: usersIds[3],
        role: "member",
        joinedAt: "2024-01-31",
        isSuspended: false,
      },
      {
        id: usersIds[4],
        role: "member",
        joinedAt: "2024-02-07",
        isSuspended: false,
      },
    ],
    createdAt: "2024-01-08",
    updatedAt: "2024-02-10",
    imageUrl: discoverNewReads,
    ownerId: usersIds[0],
    isPublic: true,
    isActive: true,
    rating: 4.6,
    tags: ["fantasy", "high fantasy", "epic fantasy"],
    location: "Online",
    meetingFrequency: "Weekly",
    nextMeeting: "2024-03-12T19:30:00Z",
    lastMeeting: "2024-02-26T19:30:00Z",
    meetingPlatform: "Discord",
    currentBook: {
      bookId: "6",
      status: "current",
      startDate: "2024-02-18",
      addedBy: usersIds[0],
      addedAt: "2024-02-01",
    },
    books: [
      {
        bookId: "6",
        status: "current",
        startDate: "2024-02-18",
        addedBy: usersIds[0],
        addedAt: "2024-02-01",
        lastUpdatedBy: usersIds[1],
      },
      {
        bookId: "7",
        status: "upcoming",
        addedBy: usersIds[1],
        addedAt: "2024-02-10",
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Historical Fiction Lovers",
    description: "A club for fans of historical novels and period dramas.",
    members: [
      {
        id: usersIds[5],
        role: "owner",
        joinedAt: "2024-01-12",
        isSuspended: false,
      },
      {
        id: usersIds[6],
        role: "moderator",
        joinedAt: "2024-01-19",
        isSuspended: false,
      },
      {
        id: usersIds[7],
        role: "member",
        joinedAt: "2024-01-26",
        isSuspended: false,
      },
      {
        id: usersIds[8],
        role: "member",
        joinedAt: "2024-02-03",
        isSuspended: false,
      },
      {
        id: usersIds[9],
        role: "member",
        joinedAt: "2024-02-10",
        isSuspended: false,
      },
    ],
    createdAt: "2024-01-10",
    updatedAt: "2024-02-15",
    imageUrl: discoverNewReads,
    ownerId: usersIds[5],
    isPublic: true,
    isActive: true,
    rating: 4.7,
    tags: ["historical fiction", "period drama", "historical novel"],
    location: "Online",
    meetingFrequency: "Bi-weekly",
    nextMeeting: "2024-03-15T20:00:00Z",
    lastMeeting: "2024-02-28T20:00:00Z",
    meetingPlatform: "Zoom",
    currentBook: {
      bookId: "8",
      status: "current",
      startDate: "2024-02-20",
      addedBy: usersIds[5],
      addedAt: "2024-02-05",
    },
    books: [
      {
        bookId: "8",
        status: "current",
        startDate: "2024-02-20",
        addedBy: usersIds[5],
        addedAt: "2024-02-05",
        lastUpdatedBy: usersIds[6],
      },
      {
        bookId: "9",
        status: "upcoming",
        addedBy: usersIds[6],
        addedAt: "2024-02-12",
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Literary Critique",
    description: "A club for discussing and analyzing literary works.",
    members: [
      {
        id: usersIds[7],
        role: "owner",
        joinedAt: "2024-01-15",
        isSuspended: false,
      },
      {
        id: usersIds[11],
        role: "moderator",
        joinedAt: "2024-01-22",
        isSuspended: false,
      },
      {
        id: usersIds[12],
        role: "member",
        joinedAt: "2024-01-29",
        isSuspended: false,
      },
      {
        id: usersIds[13],
        role: "member",
        joinedAt: "2024-02-06",
        isSuspended: false,
      },
      {
        id: usersIds[14],
        role: "member",
        joinedAt: "2024-02-13",
        isSuspended: false,
      },
    ],
    createdAt: "2024-01-12",
    updatedAt: "2024-02-18",
    imageUrl: discoverNewReads,
    ownerId: usersIds[10],
    isPublic: true,
    isActive: true,
    rating: 4.8,
    tags: ["literary criticism", "literary analysis", "literary theory"],
    location: "Online",
    meetingFrequency: "Weekly",
    nextMeeting: "2024-03-20T19:00:00Z",
    lastMeeting: "2024-03-06T19:00:00Z",
    meetingPlatform: "Discord",
    currentBook: {
      bookId: "10",
      status: "current",
      startDate: "2024-02-25",
      addedBy: usersIds[10],
      addedAt: "2024-02-10",
    },
    books: [
      {
        bookId: "10",
        status: "current",
        startDate: "2024-02-25",
        addedBy: usersIds[10],
        addedAt: "2024-02-10",
        lastUpdatedBy: usersIds[11],
      },
      {
        bookId: "11",
        status: "upcoming",
        addedBy: usersIds[11],
        addedAt: "2024-02-17",
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Science Fiction & Fantasy",
    description: "A club for fans of science fiction and fantasy literature.",
    members: [
      {
        id: usersIds[0],
        role: "owner",
        joinedAt: "2024-01-18",
        isSuspended: false,
      },
      {
        id: usersIds[1],
        role: "moderator",
        joinedAt: "2024-01-25",
        isSuspended: false,
      },
      {
        id: usersIds[2],
        role: "member",
        joinedAt: "2024-02-02",
        isSuspended: false,
      },
      {
        id: usersIds[3],
        role: "member",
        joinedAt: "2024-02-09",
        isSuspended: false,
      },
      {
        id: usersIds[4],
        role: "member",
        joinedAt: "2024-02-16",
        isSuspended: false,
      },
    ],
    createdAt: "2024-01-15",
    updatedAt: "2024-02-20",
    imageUrl: discoverNewReads,
    ownerId: usersIds[0],
    isPublic: true,
    isActive: true,
    rating: 4.6,
    tags: ["science fiction", "fantasy", "sci-fi literature"],
    location: "Online",
    meetingFrequency: "Bi-weekly",
    nextMeeting: "2024-03-25T20:00:00Z",
    lastMeeting: "2024-03-11T20:00:00Z",
    meetingPlatform: "Zoom",
    currentBook: {
      bookId: "12",
      status: "current",
      startDate: "2024-02-28",
      addedBy: usersIds[0],
      addedAt: "2024-02-15",
    },
    books: [
      {
        bookId: "12",
        status: "current",
        startDate: "2024-02-28",
        addedBy: usersIds[0],
        addedAt: "2024-02-15",
        lastUpdatedBy: usersIds[1],
      },
      {
        bookId: "13",
        status: "upcoming",
        addedBy: usersIds[1],
        addedAt: "2024-02-22",
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Dystopian & Post-Apocalyptic",
    description: "A club for fans of dystopian and post-apocalyptic literature.",
    members: [
      {
        id: usersIds[5],
        role: "owner",
        joinedAt: "2024-01-20",
        isSuspended: false,
      },
      {
        id: usersIds[6],
        role: "moderator",
        joinedAt: "2024-01-27",
        isSuspended: false,
      },
      {
        id: usersIds[7],
        role: "member",
        joinedAt: "2024-02-04",
        isSuspended: false,
      },
      {
        id: usersIds[8],
        role: "member",
        joinedAt: "2024-02-11",
        isSuspended: false,
      },
      {
        id: usersIds[9],
        role: "member",
        joinedAt: "2024-02-18",
        isSuspended: false,
      },
    ],
    createdAt: "2024-01-18",
    updatedAt: "2024-02-22",
    imageUrl: discoverNewReads,
    ownerId: usersIds[5],
    isPublic: true,
    isActive: true,
    rating: 4.7,
    tags: ["dystopian", "post-apocalyptic", "apocalyptic literature"],
    location: "Online",
    meetingFrequency: "Weekly",
    nextMeeting: "2024-03-28T19:00:00Z",
    lastMeeting: "2024-03-14T19:00:00Z",
    meetingPlatform: "Discord",
    currentBook: {
      bookId: "14",
      status: "current",
      startDate: "2024-02-28",
      addedBy: usersIds[5],
      addedAt: "2024-02-18",
    },
    books: [
      {
        bookId: "14",
        status: "current",
        startDate: "2024-02-28",
        addedBy: usersIds[5],
        addedAt: "2024-02-18",
        lastUpdatedBy: usersIds[6],
      },
      {
        bookId: "15",
        status: "upcoming",
        addedBy: usersIds[6],
        addedAt: "2024-02-25",
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Romance Novels",
    description: "A club for fans of romantic and contemporary romance novels.",
    members: [
      {
        id: usersIds[10],
        role: "owner",
        joinedAt: "2024-01-22",
        isSuspended: false,
      },
      {
        id: usersIds[11],
        role: "moderator",
        joinedAt: "2024-01-29",
        isSuspended: false,
      },
      {
        id: usersIds[12],
        role: "member",
        joinedAt: "2024-02-06",
        isSuspended: false,
      },
      {
        id: usersIds[13],
        role: "member",
        joinedAt: "2024-02-13",
        isSuspended: false,
      },
      {
        id: usersIds[14],
        role: "member",
        joinedAt: "2024-02-20",
        isSuspended: false,
      },
    ],
    createdAt: "2024-01-20",
    updatedAt: "2024-02-25",
    imageUrl: discoverNewReads,
    ownerId: usersIds[10],
    isPublic: true,
    isActive: true,
    rating: 4.5,
    tags: ["romance", "romantic", "contemporary romance"],
    location: "Online",
    meetingFrequency: "Bi-weekly",
    nextMeeting: "2024-03-30T20:00:00Z",
    lastMeeting: "2024-03-16T20:00:00Z",
    meetingPlatform: "Zoom",
    currentBook: {
      bookId: "16",
      status: "current",
      startDate: "2024-02-28",
      addedBy: usersIds[10],
      addedAt: "2024-02-20",
    },
    books: [
      {
        bookId: "16",
        status: "current",
        startDate: "2024-02-28",
        addedBy: usersIds[10],
        addedAt: "2024-02-20",
        lastUpdatedBy: usersIds[11],
      },
      {
        bookId: "17",
        status: "upcoming",
        addedBy: usersIds[11],
        addedAt: "2024-02-27",
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Young Adult Fiction",
    description: "A club for fans of young adult and middle grade fiction.",
    members: [
      {
        id: usersIds[10],
        role: "owner",
        joinedAt: "2024-01-22",
        isSuspended: false,
      },
      {
        id: usersIds[11],
        role: "moderator",
        joinedAt: "2024-01-29",
        isSuspended: false,
      },
      {
        id: usersIds[12],
        role: "member",
        joinedAt: "2024-02-06",
        isSuspended: false,
      },
      {
        id: usersIds[13],
        role: "member",
        joinedAt: "2024-02-13",
        isSuspended: false,
      },
      {
        id: usersIds[14],
        role: "member",
        joinedAt: "2024-02-20",
        isSuspended: false,
      },
    ],
    createdAt: "2024-01-22",
    updatedAt: "2024-02-27",
    imageUrl: discoverNewReads,
    ownerId: usersIds[10],
    isPublic: true,
    isActive: true,
    rating: 4.6,
    tags: ["young adult", "middle grade", "YA fiction"],
    location: "Online",
    meetingFrequency: "Weekly",
    nextMeeting: "2024-03-31T19:30:00Z",
    lastMeeting: "2024-03-17T19:30:00Z",
    meetingPlatform: "Discord",
    currentBook: {
      bookId: "18",
      status: "current",
      startDate: "2024-02-28",
      addedBy: usersIds[10],
      addedAt: "2024-02-22",
    },
    books: [
      {
        bookId: "18",
        status: "current",
        startDate: "2024-02-28",
        addedBy: usersIds[10],
        addedAt: "2024-02-22",
        lastUpdatedBy: usersIds[11],
      },
      {
        bookId: "19",
        status: "upcoming",
        addedBy: usersIds[11],
        addedAt: "2024-02-27",
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Non-Fiction Bookworms",
    description: "A club for fans of non-fiction books and memoirs.",
    members: [
      {
        id: usersIds[15],
        role: "owner",
        joinedAt: "2024-01-24",
        isSuspended: false,
      },
      {
        id: usersIds[7],
        role: "moderator",
        joinedAt: "2024-01-31",
        isSuspended: false,
      },
      {
        id: usersIds[5],
        role: "member",
        joinedAt: "2024-02-07",
        isSuspended: false,
      },
      {
        id: usersIds[14],
        role: "member",
        joinedAt: "2024-02-14",
        isSuspended: false,
      },
      {
        id: usersIds[11],
        role: "member",
        joinedAt: "2024-02-21",
        isSuspended: false,
      },
    ],
    createdAt: "2024-01-24",
    updatedAt: "2024-02-29",
    imageUrl: discoverNewReads,
    ownerId: usersIds[15],
    isPublic: true,
    isActive: true,
    rating: 4.7,
    tags: ["non-fiction", "memoir", "biography"],
    location: "Online",
    meetingFrequency: "Bi-weekly",
    nextMeeting: "2024-03-31T20:00:00Z",
    lastMeeting: "2024-03-17T20:00:00Z",
    meetingPlatform: "Zoom",
    currentBook: {
      bookId: "20",
      status: "current",
      startDate: "2024-02-28",
      addedBy: usersIds[15],
      addedAt: "2024-02-24",
    },
    books: [
      {
        bookId: "20",
        status: "current",
        startDate: "2024-02-28",
        addedBy: usersIds[15],
        addedAt: "2024-02-24",
        lastUpdatedBy: usersIds[2],
      },
      {
        bookId: "21",
        status: "upcoming",
        addedBy: usersIds[1],
        addedAt: "2024-02-28",
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Literary Classics",
    description: "A club for fans of classic literature and literary history.",
    members: [
      {
        id: usersIds[7],
        role: "owner",
        joinedAt: "2024-01-26",
        isSuspended: false,
      },
      {
        id: usersIds[11],
        role: "moderator",
        joinedAt: "2024-02-02",
        isSuspended: false,
      },
      {
        id: usersIds[8],
        role: "member",
        joinedAt: "2024-02-09",
        isSuspended: false,
      },
      {
        id: usersIds[2],
        role: "member",
        joinedAt: "2024-02-16",
        isSuspended: false,
      },
      {
        id: usersIds[9],
        role: "member",
        joinedAt: "2024-02-23",
        isSuspended: false,
      },
    ],
    createdAt: "2024-01-26",
    updatedAt: "2024-02-29",
    imageUrl: discoverNewReads,
    ownerId: usersIds[5],
    isPublic: true,
    isActive: true,
    rating: 4.8,
    tags: ["classic literature", "literary history", "literary classics"],
    location: "Online",
    meetingFrequency: "Bi-weekly",
    nextMeeting: "2024-03-31T19:00:00Z",
    lastMeeting: "2024-03-17T19:00:00Z",
    meetingPlatform: "Discord",
    currentBook: {
      bookId: "22",
      status: "current",
      startDate: "2024-02-28",
      addedBy: usersIds[13],
      addedAt: "2024-02-26",
    },
    books: [
      {
        bookId: "22",
        status: "current",
        startDate: "2024-02-28",
        addedBy: usersIds[3],
        addedAt: "2024-02-26",
        lastUpdatedBy: usersIds[13],
      },
      {
        bookId: "23",
        status: "upcoming",
        addedBy: usersIds[8],
        addedAt: "2024-02-27",
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Science & Technology",
    description: "A club for fans of science and technology books.",
    members: [
      {
        id: usersIds[1],
        role: "owner",
        joinedAt: "2024-01-28",
        isSuspended: false,
      },
      {
        id: usersIds[6],
        role: "moderator",
        joinedAt: "2024-02-04",
        isSuspended: false,
      },
      {
        id: usersIds[7],
        role: "member",
        joinedAt: "2024-02-11",
        isSuspended: false,
      },
      {
        id: usersIds[3],
        role: "member",
        joinedAt: "2024-02-18",
        isSuspended: false,
      },
      {
        id: usersIds[9],
        role: "member",
        joinedAt: "2024-02-25",
        isSuspended: false,
      },
    ],
    createdAt: "2024-01-28",
    updatedAt: "2024-02-29",
    imageUrl: discoverNewReads,
    ownerId: usersIds[5],
    isPublic: true,
    isActive: true,
    rating: 4.6,
    tags: ["science", "technology", "science books"],
    location: "Online",
    meetingFrequency: "Bi-weekly",
    nextMeeting: "2024-03-31T20:00:00Z",
    lastMeeting: "2024-03-17T20:00:00Z",
    meetingPlatform: "Zoom",
    currentBook: {
      bookId: "24",
      status: "current",
      startDate: "2024-02-28",
      addedBy: usersIds[8],
      addedAt: "2024-02-28",
    },
    books: [
      {
        bookId: "24",
        status: "current",
        startDate: "2024-02-28",
        addedBy: usersIds[10],
        addedAt: "2024-02-28",
        lastUpdatedBy: usersIds[6],
      },
      {
        bookId: "25",
        status: "upcoming",
        addedBy: usersIds[12],
        addedAt: "2024-02-28",
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Travel Literature",
    description: "A club for fans of travel literature and adventure stories.",
    members: [
      {
        id: usersIds[10],
        role: "owner",
        joinedAt: "2024-01-30",
        isSuspended: false,
      },
      {
        id: usersIds[11],
        role: "moderator",
        joinedAt: "2024-02-06",
        isSuspended: false,
      },
      {
        id: usersIds[12],
        role: "member",
        joinedAt: "2024-02-13",
        isSuspended: false,
      },
      {
        id: usersIds[3],
        role: "member",
        joinedAt: "2024-02-20",
        isSuspended: false,
      },
      {
        id: usersIds[14],
        role: "member",
        joinedAt: "2024-02-27",
        isSuspended: false,
      },
    ],
    createdAt: "2024-01-30",
    updatedAt: "2024-02-29",
    imageUrl: discoverNewReads,
    ownerId: usersIds[14],
    isPublic: true,
    isActive: true,
    rating: 4.7,
    tags: ["travel literature", "adventure", "travel stories"],
    location: "Online",
    meetingFrequency: "Weekly",
    nextMeeting: "2024-03-31T19:00:00Z",
    lastMeeting: "2024-03-17T19:00:00Z",
    meetingPlatform: "Discord",
    currentBook: {
      bookId: "26",
      status: "current",
      startDate: "2024-02-28",
      addedBy: usersIds[8],
      addedAt: "2024-02-30",
    },
    books: [
      {
        bookId: "26",
        status: "current",
        startDate: "2024-02-28",
        addedBy: usersIds[10],
        addedAt: "2024-02-30",
        lastUpdatedBy: usersIds[5],
      },
      {
        bookId: "27",
        status: "upcoming",
        addedBy: usersIds[10],
        addedAt: "2024-02-27",
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Literary Fiction",
    description: "A club for fans of literary fiction and modernist literature.",
    members: [
      {
        id: usersIds[1],
        role: "owner",
        joinedAt: "2024-02-01",
        isSuspended: false,
      },
      {
        id: usersIds[11],
        role: "moderator",
        joinedAt: "2024-02-08",
        isSuspended: false,
      },
      {
        id: usersIds[7],
        role: "member",
        joinedAt: "2024-02-15",
        isSuspended: false,
      },
      {
        id: usersIds[2],
        role: "member",
        joinedAt: "2024-02-22",
        isSuspended: false,
      },
      {
        id: usersIds[6],
        role: "member",
        joinedAt: "2024-02-29",
        isSuspended: false,
      },
    ],
    createdAt: "2024-02-01",
    updatedAt: "2024-02-29",
    imageUrl: discoverNewReads,
    ownerId: usersIds[1],
    isPublic: true,
    isActive: true,
    rating: 4.7,
    tags: ["literary fiction", "modernist", "modernist literature"],
    location: "Online",
    meetingFrequency: "Bi-weekly",
    nextMeeting: "2024-03-31T20:00:00Z",
    lastMeeting: "2024-03-17T20:00:00Z",
    meetingPlatform: "Discord",
    currentBook: {
      bookId: "28",
      status: "current",
      startDate: "2024-02-28",
      addedBy: usersIds[5],
      addedAt: "2024-02-01",
    },
    books: [
      {
        bookId: "28",
        status: "current",
        startDate: "2024-02-28",
        addedBy: usersIds[3],
        addedAt: "2024-02-01",
        lastUpdatedBy: usersIds[9],
      },
      {
        bookId: "29",
        status: "upcoming",
        addedBy: usersIds[7],
        addedAt: "2024-02-08",
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Historical Mystery",
    description: "A club for fans of historical mysteries and period crime novels.",
    members: [
      {
        id: usersIds[11],
        role: "owner",
        joinedAt: "2024-02-03",
        isSuspended: false,
      },
      {
        id: usersIds[4],
        role: "moderator",
        joinedAt: "2024-02-10",
        isSuspended: false,
      },
      {
        id: usersIds[2],
        role: "member",
        joinedAt: "2024-02-17",
        isSuspended: false,
      },
      {
        id: usersIds[13],
        role: "member",
        joinedAt: "2024-02-24",
        isSuspended: false,
      },
      {
        id: usersIds[11],
        role: "member",
        joinedAt: "2024-03-03",
        isSuspended: false,
      },
    ],
    createdAt: "2024-02-03",
    updatedAt: "2024-02-29",
    imageUrl: discoverNewReads,
    ownerId: usersIds[8],
    isPublic: true,
    isActive: true,
    rating: 4.8,
    tags: ["historical mystery", "period crime", "historical crime"],
    location: "Online",
    meetingFrequency: "Bi-weekly",
    nextMeeting: "2024-03-31T19:00:00Z",
    lastMeeting: "2024-03-17T19:00:00Z",
    meetingPlatform: "Discord",
    currentBook: {
      bookId: "30",
      status: "current",
      startDate: "2024-02-28",
      addedBy: usersIds[10],
      addedAt: "2024-02-03",
    },
    books: [
      {
        bookId: "30",
        status: "current",
        startDate: "2024-02-28",
        addedBy: usersIds[7],
        addedAt: "2024-02-03",
        lastUpdatedBy: usersIds[6],
      },
      {
        bookId: "31",
        status: "upcoming",
        addedBy: usersIds[6],
        addedAt: "2024-02-10",
      },
    ],
  },
];