import trackYourProgress from "../assets/track_your_progress.png";
import keepingInTouch from "../assets/keeping_in_touch.png";
import discoverNewReads from "../assets/discover_new_reads.png"

export type clubMember = {
  id: string;
  role?: "member" | "moderator" | "owner";
  joinedAt: string;
  isSuspended: boolean;
}

export type bookClub = {
  id: string;
  name: string;
  description: string;
  members: clubMember[];
  createdAt: string;
  updatedAt: string;
  imageUrl?: string;
  ownerId: string;
  isPublic: boolean;
  isActive: boolean;
  rating: number;
  tags?: string[];
  location?: string;
  meetingFrequency?: string;
  nextMeeting?: string;
  lastMeeting?: string;
  meetingPlatform?: string;
}

export const defaultBookClubs: bookClub[] = [
  {
    id: "1",
    name: "Book Lovers",
    description: "A club for people who love reading books.",
    members: [
      {
        id: "user1",
        joinedAt: new Date().toISOString(),
        isSuspended: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageUrl: discoverNewReads,
    ownerId: "user1",
    isPublic: true,
    isActive: true,
    rating: 4.5,
    tags: ["fiction", "mystery"],
    location: "Online",
    meetingFrequency: "Weekly",
    nextMeeting: new Date().toISOString(),
    lastMeeting: new Date().toISOString(),
    meetingPlatform: "Zoom",
  },
  {
    id: "2",
    name: "Sci-Fi Enthusiasts",
    description: "A club for fans of science fiction.",
    members: [
      {
        id: "user3",
        joinedAt: new Date().toISOString(),
        isSuspended: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageUrl: keepingInTouch,
    ownerId: "user3",
    isPublic: true,
    isActive: true,
    rating: 4.0,
    tags: ["science fiction", "fantasy"],
    location: "Online",
    meetingFrequency: "Bi-weekly",
    nextMeeting: new Date().toISOString(),
    lastMeeting: new Date().toISOString(),
    meetingPlatform: "Discord",
  },
  {
    id: "3",
    name: "Mystery Solvers",
    description: "A club for those who love solving mysteries.",
    members: [
      {
        id: "user5",
        role: "member",
        joinedAt: new Date().toISOString(),
        isSuspended: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageUrl: keepingInTouch,
    ownerId: "user5",
    isPublic: true,
    isActive: true,
    rating: 4.8,
    tags: ["mystery", "thriller"],
    location: "Online",
    meetingFrequency: "Monthly",
    nextMeeting: new Date().toISOString(),
    lastMeeting: new Date().toISOString(),
    meetingPlatform: "Google Meet",
  },
  {
    id: "4",
    name: "History Buffs",
    description: "A club for those who love history books.",
    members: [
      {
        id: "user7",
        joinedAt: new Date().toISOString(),
        isSuspended: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageUrl: keepingInTouch,
    ownerId: "user7",
    isPublic: true,
    isActive: true,
    rating: 3.5,
    tags: ["history", "non-fiction"],
    location: "Online",
    meetingFrequency: "Monthly",
    nextMeeting: new Date().toISOString(),
    lastMeeting: new Date().toISOString(),
    meetingPlatform: "Skype",
  },
  {
    id: "5",
    name: "Fantasy Realm",
    description: "A club for fans of fantasy novels.",
    members: [
      {
        id: "user9",
        joinedAt: new Date().toISOString(),
        isSuspended: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageUrl: discoverNewReads,
    ownerId: "user9",
    isPublic: true,
    isActive: true,
    rating: 4.2,
    tags: ["fantasy", "adventure"],
    location: "Online",
    meetingFrequency: "Weekly",
    nextMeeting: new Date().toISOString(),
    lastMeeting: new Date().toISOString(),
    meetingPlatform: "Teams",
  },
  {
    id: "6",
    name: "Romance Readers",
    description: "A club for those who love romance novels.",
    members: [
      {
        id: "user11",
        joinedAt: new Date().toISOString(),
        isSuspended: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageUrl: keepingInTouch,
    ownerId: "user11",
    isPublic: true,
    isActive: true,
    rating: 4.5,
    tags: ["romance", "fiction"],
    location: "Online",
    meetingFrequency: "Bi-Monthly",
    nextMeeting: new Date().toISOString(),
    lastMeeting: new Date().toISOString(),
    meetingPlatform: "Zoom",
  },
  {
    id: "7",
    name: "Science Fiction Fans",
    description: "A club for fans of science fiction novels.",
    members: [
      {
        id: "user13",
        joinedAt: new Date().toISOString(),
        isSuspended: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageUrl: keepingInTouch,
    ownerId: "user13",
    isPublic: true,
    isActive: true,
    rating: 4.1,
    tags: ["science fiction", "space opera"],
    location: "Online",
    meetingFrequency: "Monthly",
    nextMeeting: new Date().toISOString(),
    lastMeeting: new Date().toISOString(),
    meetingPlatform: "Discord",
  },
  {
    id: "8",
    name: "Horror Enthusiasts",
    description: "A club for those who love horror novels.",
    members: [
      {
        id: "user15",
        joinedAt: new Date().toISOString(),
        isSuspended: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageUrl: discoverNewReads,
    ownerId: "user15",
    isPublic: true,
    isActive: true,
    rating: 4.3,
    tags: ["horror", "paranormal"],
    location: "Online",
    meetingFrequency: "Quarterly",
    nextMeeting: new Date().toISOString(),
    lastMeeting: new Date().toISOString(),
    meetingPlatform: "Google Meet",
  },
  {
    id: "9",
    name: "Classics Club",
    description: "A club for those who love classic literature.",
    members: [
      {
        id: "user17",
        role: "member",
        joinedAt: new Date().toISOString(),
        isSuspended: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageUrl: trackYourProgress,
    ownerId: "user17",
    isPublic: true,
    isActive: true,
    rating: 4.6,
    tags: ["classics", "literary fiction"],
    location: "Online",
    meetingFrequency: "Bi-Monthly",
    nextMeeting: new Date().toISOString(),
    lastMeeting: new Date().toISOString(),
    meetingPlatform: "Skype",
  },
  {
    id: "10",
    name: "Graphic Novel Guild",
    description: "A club for fans of graphic novels.",
    members: [
      {
        id: "user19",
        joinedAt: new Date().toISOString(),
        isSuspended: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageUrl: discoverNewReads,
    ownerId: "user19",
    isPublic: true,
    isActive: true,
    rating: 4.4,
    tags: ["graphic novels", "comics"],
    location: "Online",
    meetingFrequency: "Monthly",
    nextMeeting: new Date().toISOString(),
    lastMeeting: new Date().toISOString(),
    meetingPlatform: "Teams",
  },
  {
    id: "11",
    name: "Poetry Circle",
    description: "A club for those who love poetry.",
    members: [
      {
        id: "user21",
        joinedAt: new Date().toISOString(),
        isSuspended: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageUrl: trackYourProgress,
    ownerId: "user21",
    isPublic: true,
    isActive: true,
    rating: 4.7,
    tags: ["poetry", "literary"],
    location: "Online",
    meetingFrequency: "Bi-Monthly",
    nextMeeting: new Date().toISOString(),
    lastMeeting: new Date().toISOString(),
    meetingPlatform: "Zoom",
  },
  {
    id: "12",
    name: "Biography Book Club",
    description: "A club for those who love biographies.",
    members: [
      {
        id: "user23",
        role: "moderator",
        joinedAt: new Date().toISOString(),
        isSuspended: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageUrl: trackYourProgress,
    ownerId: "user23",
    isPublic: true,
    isActive: true,
    rating: 4.0,
    tags: ["biography", "non-fiction"],
    location: "Online",
    meetingFrequency: "Quarterly",
    nextMeeting: new Date().toISOString(),
    lastMeeting: new Date().toISOString(),
    meetingPlatform: "Discord",
  },
  {
    id: "13",
    name: "Memoir Lovers",
    description: "A club for those who love memoirs.",
    members: [
      {
        id: "user25",
        joinedAt: new Date().toISOString(),
        isSuspended: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageUrl: keepingInTouch,
    ownerId: "user25",
    isPublic: true,
    isActive: true,
    rating: 4.9,
    tags: ["memoir", "non-fiction"],
    location: "Online",
    meetingFrequency: "Bi-Monthly",
    nextMeeting: new Date().toISOString(),
    lastMeeting: new Date().toISOString(),
    meetingPlatform: "Google Meet",
  },
  {
    id: "14",
    name: "Philosophy Discussion",
    description: "A club for those who love philosophical discussions.",
    members: [
      {
        id: "user27",
        joinedAt: new Date().toISOString(),
        isSuspended: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageUrl: trackYourProgress,
    ownerId: "user27",
    isPublic: true,
    isActive: true,
    rating: 4.8,
    tags: ["philosophy", "non-fiction"],
    location: "Online",
    meetingFrequency: "Monthly",
    nextMeeting: new Date().toISOString(),
    lastMeeting: new Date().toISOString(),
    meetingPlatform: "Skype",
  },
  {
    id: "15",
    name: "Young Adult Fiction",
    description: "A club for fans of young adult fiction.",
    members: [
      {
        id: "user29",
        role: "member",
        joinedAt: new Date().toISOString(),
        isSuspended: false,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageUrl: discoverNewReads,
    ownerId: "user29",
    isPublic: true,
    isActive: true,
    rating: 4.6,
    tags: ["young adult", "fiction"],
    location: "Online",
    meetingFrequency: "Bi-Monthly",
    nextMeeting: new Date().toISOString(),
    lastMeeting: new Date().toISOString(),
    meetingPlatform: "Teams",
  },
]