import type { User } from "../types/user";
import { v4 as uuidv4 } from "uuid";

const userIds = () => {
  const ids: string[] = [];
  for (let i = 0; i < 15; i++) {
    ids.push(uuidv4());
  }
  return ids;
};

export const usersIds = userIds();

export const UsersData: User[] = [
  {
    id: usersIds[0],
    name: "Alice Johnson",
    email: "alice@example.com",
    pwd: "password",
    joinedAt: "2023-06-15",
    isActive: true,
    bio: "Book enthusiast and writer",
    books: [],
  },
  {
    id: usersIds[1],
    name: "Bob Smith",
    email: "bob@example.com",
    pwd: "password",
    joinedAt: "2023-07-20",
    isActive: true,
    bio: "Sci-fi lover",
    books: [
      {
        bookId: "2",
        status: "reading",
        progress: 80,
        addedAt: "2024-02-05",
        startedAt: "2024-02-10",
      },
      {
        bookId: "5",
        status: "completed",
        progress: 100,
        rating: 5,
        addedAt: "2023-10-25",
        startedAt: "2023-11-01",
        completedAt: "2024-01-15",
      },
      {
        bookId: "6",
        status: "reading",
        progress: 40,
        addedAt: "2024-01-30",
        startedAt: "2024-02-05",
      },
      {
        bookId: "7",
        status: "completed",
        progress: 100,
        rating: 5,
        addedAt: "2024-01-05",
        startedAt: "2024-01-10",
        completedAt: "2024-01-25",
      },
    ],
  },
  {
    id: usersIds[2],
    name: "Carol Davis",
    email: "carol@example.com",
    pwd: "password",
    joinedAt: "2023-08-10",
    isActive: true,
    bio: "Mystery novel enthusiast",
    books: [
      {
        bookId: "1",
        status: "reading",
        progress: 75,
        addedAt: "2024-01-25",
        startedAt: "2024-02-01",
      },
      {
        bookId: "6",
        status: "reading",
        progress: 90,
        addedAt: "2024-01-15",
        startedAt: "2024-01-20",
      },
    ],
  },
  {
    id: usersIds[3],
    name: "David Wilson",
    email: "david@example.com",
    pwd: "password",
    joinedAt: "2023-09-05",
    isActive: true,
    bio: "Classic literature reader",
    books: [
      {
        bookId: "3",
        status: "reading",
        progress: 20,
        addedAt: "2024-02-03",
        startedAt: "2024-02-08",
      },
      {
        bookId: "7",
        status: "reading",
        progress: 30,
        addedAt: "2024-01-26",
        startedAt: "2024-02-01",
      },
    ],
  },
  {
    id: usersIds[4],
    name: "Emma Brown",
    email: "emma@example.com",
    pwd: "password",
    joinedAt: "2023-09-15",
    isActive: true,
    bio: "Fantasy fiction fan",
    books: [
      {
        bookId: "1",
        status: "completed",
        progress: 100,
        rating: 5,
        addedAt: "2023-11-25",
        startedAt: "2023-12-01",
        completedAt: "2024-01-20",
      },
      {
        bookId: "4",
        status: "to-read",
        progress: 0,
        addedAt: "2024-02-10",
      },
    ],
  },
  {
    id: usersIds[5],
    name: "Frank Lee",
    email: "frank@example.com",
    pwd: "password",
    joinedAt: "2023-10-01",
    isActive: true,
    bio: "Historical fiction reader",
    books: [
      {
        bookId: "2",
        status: "reading",
        progress: 45,
        addedAt: "2024-02-01",
        startedAt: "2024-02-05",
      },
      {
        bookId: "7",
        status: "reading",
        progress: 75,
        addedAt: "2024-01-23",
        startedAt: "2024-01-28",
      },
    ],
  },
  {
    id: usersIds[6],
    name: "Grace Taylor",
    email: "grace@example.com",
    pwd: "password",
    joinedAt: "2023-10-12",
    isActive: true,
    bio: "Book club moderator",
    books: [
      {
        bookId: "3",
        status: "to-read",
        progress: 0,
        addedAt: "2024-02-05",
      },
      {
        bookId: "5",
        status: "to-read",
        progress: 0,
        addedAt: "2024-01-15",
      },
    ],
  },
  {
    id: usersIds[7],
    name: "Henry Martinez",
    email: "henry@example.com",
    pwd: "password",
    joinedAt: "2023-10-25",
    isActive: true,
    bio: "Thriller enthusiast",
    books: [
      {
        bookId: "2",
        status: "completed",
        progress: 100,
        rating: 4,
        addedAt: "2024-01-10",
        startedAt: "2024-01-15",
        completedAt: "2024-02-01",
      },
    ],
  },
  {
    id: usersIds[8],
    name: "Isabella Garcia",
    email: "isabella@example.com",
    pwd: "password",
    joinedAt: "2023-11-05",
    isActive: true,
    bio: "Poetry lover",
    books: [
      {
        bookId: "4",
        status: "reading",
        progress: 35,
        addedAt: "2024-01-26",
        startedAt: "2024-02-01",
      },
    ],
  },
  {
    id: usersIds[9],
    name: "Jack Anderson",
    email: "jack@example.com",
    pwd: "password",
    joinedAt: "2023-11-15",
    isActive: true,
    bio: "Non-fiction reader",
    books: [
      {
        bookId: "3",
        status: "reading",
        progress: 60,
        addedAt: "2024-01-20",
        startedAt: "2024-01-25",
      },
      {
        bookId: "6",
        status: "reading",
        progress: 65,
        addedAt: "2024-01-26",
        startedAt: "2024-02-01",
      },
    ],
  },
  {
    id: usersIds[10],
    name: "Kate Williams",
    email: "kate@example.com",
    pwd: "password",
    joinedAt: "2023-11-25",
    isActive: true,
    bio: "Young adult fiction",
    books: [
      {
        bookId: "1",
        status: "completed",
        progress: 100,
        rating: 5,
        addedAt: "2023-12-25",
        startedAt: "2024-01-01",
        completedAt: "2024-01-15",
      },
      {
        bookId: "5",
        status: "reading",
        progress: 50,
        addedAt: "2024-01-15",
        startedAt: "2024-01-20",
      },
    ],
  },
  {
    id: usersIds[11],
    name: "Luke Thompson",
    email: "luke@example.com",
    pwd: "password",
    joinedAt: "2023-12-01",
    isActive: true,
    bio: "Horror genre fan",
    books: [
      {
        bookId: "4",
        status: "reading",
        progress: 10,
        addedAt: "2024-02-10",
        startedAt: "2024-02-15",
      },
    ],
  },
  {
    id: usersIds[12],
    name: "Maya Rodriguez",
    email: "maya@example.com",
    pwd: "password",
    joinedAt: "2023-12-10",
    isActive: true,
    bio: "Biography reader",
    books: [],
  },
  {
    id: usersIds[13],
    name: "Nathan White",
    email: "nathan@example.com",
    pwd: "password",
    joinedAt: "2023-12-20",
    isActive: true,
    bio: "Philosophy books",
    books: [],
  },
  {
    id: usersIds[14],
    name: "Olivia Harris",
    email: "olivia@example.com",
    pwd: "password",
    joinedAt: "2024-01-01",
    isActive: true,
    bio: "Graphic novel enthusiast",
    books: [],
  },
  {
    id: usersIds[15],
    name: "Paul Clark",
    email: "paul@example.com",
    pwd: "password",
    joinedAt: "2024-01-10",
    isActive: true,
    bio: "Literary critic",
    books: [],
  },
];
